feat: Added tables creation and population

diff --git a/.github/workflows/cd-base.yml b/.github/workflows/cd-base.yml
--- a/.github/workflows/cd-base.yml
+++ b/.github/workflows/cd-base.yml
@@ -69,7 +69,15 @@ jobs:
 
       - name: Create tables and populate (tickets table not existent)
         if: steps.check_table.outputs.table_exist == 'f'
-        run: echo ""
+        env:
+          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
+        run: |
+          # if something fails stop
+          set -e 
+          for file in $(ls src/db/scripts*.sql | sort -V); do
+            echo "> Executing: $file"
+            psql -h ${{ steps.db.outputs.public_ip }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f "$file" -v ON_ERROR_STOP=1
+          done
       
       - name: Skipped table creation (existent tickets table)
         if: steps.check_table.outputs.table_exist == 't'
